[1]: clean basetools with script
[w]: clean basetools, i don't need that more
[h]: script: 1_basetools_clean.sh
[w]: edksetup was over-design and hard to read
[h]: script: edksetup.sh(re-code)
[w]: remove test and local clean for make to match above changes
[h]: GNUmakefile: Tests(-) & localClean(-)

Signed-off-by: Liu Yi <efikarl@icloud.com>

diff --git a/BaseTools/BinWrappers/PosixLike/BrotliCompress b/BaseTools/BinWrappers/PosixLike/BrotliCompress
--- a/BaseTools/BinWrappers/PosixLike/BrotliCompress
+++ b/BaseTools/BinWrappers/PosixLike/BrotliCompress
@@ -1,34 +1,25 @@
 #!/usr/bin/env bash
 #
-# This script will exec Brotli tool with -e/-d options.
+#  Copyright ©2020 efikarl, https://efikarl.com.
 #
-# Copyright (c) 2017 - 2018, Intel Corporation. All rights reserved.<BR>
-# SPDX-License-Identifier: BSD-2-Clause-Patent
+#  This program is just made available under the terms and conditions of the
+#  MIT license: https://efikarl.com/mit-license.html.
 #
-QLT="-q 9 -w 22"
-ARGS=
+#  THE PROGRAM IS DISTRIBUTED UNDER THE MIT LICENSE ON AN "AS IS" BASIS,
+#  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
-while test $# -gt 0
-do
-  case $1 in
-    -e)
-      ;;
-    -d)
-      ARGS+="$1 "
-      ;;
-    -o|-g)
-      ARGS+="$1 $2 "
-      shift
-      ;;
-    -q)
-      QLT="$1 $2 "
-      shift
-      ;;
-    *)
-      ARGS+="$1 "
-      ;;
-  esac
-  shift
-done
-
-exec Brotli $QLT $ARGS
+THE_CMD=${BASH_SOURCE:-$0}
+CMD_DIR=$( dirname ${THE_CMD})
+CMD_EXE=$(basename ${THE_CMD})
+# 1. try to run project stardard tool
+if [[ -d $WORKSPACE ]] && [[ -e $EDK_TOOLS_PATH/Source/C ]]
+then
+  exec $EDK_TOOLS_PATH/Source/C/bin/$CMD_EXE $@
+# 2. try to run tool in system path
+elif ( command -v $CMD_EXE >/dev/null 2>&1 )
+then
+  exec $CMD_EXE $@
+else
+  echo "[ERR]:${BASH_SOURCE:-$0}: unable to find $CMD_EXE to run."
+  exit 127
+fi
